// Generated by @BindType. Do not modify!

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;

@Module
@InstallIn(CustomComponent.class)
public interface HiltBinder_CustomComponentModule {
    @Binds
    Testable bind_Test(Test binding);
}