// Generated by @BindType. Do not modify!

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;
import java.lang.Float;
import java.lang.Integer;
import java.lang.String;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
  @Binds
  Testable<Testable1<? super Integer, ? super Float, ? super String>, Testable2<? extends Integer, ? extends Float, ? extends String>, Testable3<?, ?, ?>> bind_Test(
      Test binding);
}