// Generated by @BindType. Do not modify!

import dagger.Binds;
import dagger.Module;
import dagger.hilt.InstallIn;
import dagger.hilt.components.SingletonComponent;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Float;
import java.lang.Integer;

@Module
@InstallIn(SingletonComponent.class)
public interface HiltBinder_SingletonComponentModule {
    @Binds
    @CustomQualifier(
        boolValue = true,
        byteValue = 10,
        charValue = ',',
        shortValue = 32767,
        intValue = -10,
        longValue = 100,
        floatValue = -15.0f,
        doubleValue = 50.0,
        stringValue = "string",
        enumValue = CustomQualifierType.ONE,
        annotationValue = @InnerAnno(intValue = 0, longValue = 500, classValue = CustomQualifierClass.class),
        classValue = CustomQualifierClass.class,
        boolArray = {
            true,
            false
        },
        byteArray = {
            100,
            105
        },
        charArray = {
            'A',
            'B',
            'C'
        },
        shortArray = {
            -32768,
            32767
        },
        intArray = {
            0,
            10,
            20
        },
        longArray = {
            10,
            20,
            30
        },
        floatArray = {
            3.4028235E38f,
            1.4E-45f
        },
        doubleArray = {
            100.0,
            200.0,
            300.0
        },
        stringArray = {
            "one",
            "two",
            "three"
        },
        enumArray = {
            CustomQualifierType.ONE,
            CustomQualifierType.TWO,
            CustomQualifierType.THREE
        },
        annotationArray = {
            @InnerAnno(intValue = 0, longValue = 1, classValue = Integer.class),
            @InnerAnno(intValue = 10, longValue = 100, classValue = Float.class)
        },
        classArray = {
            Boolean.class,
            Integer.class,
            Double.class
        }
    )
    Testable bind_Test(Test binding);
}